name: robustqa
channels:
  - pytorch
  - defaults
dependencies:
  - pip=20.3.1
  - python
  - numpy
  - tqdm
  - pip:
    - torch
    - tqdm
    - transformers
    - tensorboard
    - tensorflow
    - tensorboardX
    - sentence-transformers